{
 "title": "MySQL Slow Queries",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source_category", "query": "${VAR_SOURCE_CATEGORY}" }
  ]
 },
 "panels": [
  {
   "title": "Top IP Firing Slow Queries",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aliasFormat": "{{ip_addr}}",
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"  \n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\s+Tmp_tables:\\s+(?<tmp_tables>\\d*)\\s+Tmp_disk_tables:\\s+(?<temp_disk_tables>\\d*)\\s+Tmp_table_sizes:\\s+(?<tmp_table_sizes>\\d*)\\n\" nodrop // Pttrn3-vrtn1\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\n\" nodrop // Pttrn3-vrtn2\n//| parse regex field=query_block \"# InnoDB_trx_id:\\s+(?<innodb_trx_id>\\S*)\\n\"\n//| parse regex field=query_block \"# QC_Hit:\\s+(?<qc_hit>\\S*)\\s+Full_scan:\\s+(?<full_scan>\\S*)\\s+Full_join:\\s+(?<full_join>\\S+)\\s+Tmp_table:\\s+(?<tmp_table>\\S+)\\s+Tmp_table_on_disk:\\s+(?<tmp_table_on_disk>\\S+)\\n\"\n//| parse regex field=query_block \"Filesort:\\s+(?<filesort>\\S*)\\s+Filesort_on_disk:\\s+(?<filesort_on_disk>\\S*)\\s+Merge_passes:\\s+(?<merge_passes>\\S*)\\n\"\n//| parse regex field=query_block \"InnoDB_IO_r_ops:\\s+(?<innoDB_IO_r_ops>\\d*)\\s+InnoDB_IO_r_bytes:\\s+(?<innoDB_IO_r_bytes>\\d*)\\s+InnoDB_IO_r_wait:\\s+(?<innoDB_IO_r_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_rec_lock_wait:\\s+(?<innoDB_rec_lock_wait>[\\d.]*)\\s+InnoDB_queue_wait:\\s+(?<InnoDB_queue_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_pages_distinct:\\s+(?<InnoDB_pages_distinct>[\\d]*)\\n\"\n//| parse regex field=query_block \"SET timestamp=(?<set_timestamp>\\d*);\\n(?<sql_cmd>[\\s\\S]*);\"\n| fields -query_block\n| count as frequency by ip_addr | sort by frequency"
    }
   ]
  },
  {
   "title": "Top Users Firing Slow Queries",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aliasFormat": "{{user}}",
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"\n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n//| parse regex field=query_block \"SET timestamp=(?<set_timestamp>\\d*);\\n(?<sql_cmd>[\\s\\S]*);\"\n| fields -query_block\n| count as frequency by user | sort by frequency"
    }
   ]
  },
  {
   "title": "Slow Queries by Host",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aliasFormat": "{{host}}",
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"\n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n| _sourceHost as Host\n| fields -query_block\n| count as queries_count by Host | sort by queries_count"
    }
   ]
  },
  {
   "title": "Excessive Slow Queries by Host",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aliasFormat": "{{host}}",
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"\n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\s+Tmp_tables:\\s+(?<tmp_tables>\\d*)\\s+Tmp_disk_tables:\\s+(?<temp_disk_tables>\\d*)\\s+Tmp_table_sizes:\\s+(?<tmp_table_sizes>\\d*)\\n\" nodrop // Pttrn3-vrtn1\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\n\" nodrop // Pttrn3-vrtn2\n| num(query_time)\n| where (query_time >= 5)\n| _sourceHost as Host\n| fields -query_block\n| count as queries_count by Host | sort by queries_count"
    }
   ]
  },
  {
   "title": "Slow Query by Cmd Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasFormat": "{{sql_cmd_type}}",
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"\n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\s+Tmp_tables:\\s+(?<tmp_tables>\\d*)\\s+Tmp_disk_tables:\\s+(?<temp_disk_tables>\\d*)\\s+Tmp_table_sizes:\\s+(?<tmp_table_sizes>\\d*)\\n\" nodrop // Pttrn3-vrtn1\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\n\" nodrop // Pttrn3-vrtn2\n//| parse regex field=query_block \"# InnoDB_trx_id:\\s+(?<innodb_trx_id>\\S*)\\n\"\n//| parse regex field=query_block \"# QC_Hit:\\s+(?<qc_hit>\\S*)\\s+Full_scan:\\s+(?<full_scan>\\S*)\\s+Full_join:\\s+(?<full_join>\\S+)\\s+Tmp_table:\\s+(?<tmp_table>\\S+)\\s+Tmp_table_on_disk:\\s+(?<tmp_table_on_disk>\\S+)\\n\"\n//| parse regex field=query_block \"Filesort:\\s+(?<filesort>\\S*)\\s+Filesort_on_disk:\\s+(?<filesort_on_disk>\\S*)\\s+Merge_passes:\\s+(?<merge_passes>\\S*)\\n\"\n//| parse regex field=query_block \"InnoDB_IO_r_ops:\\s+(?<innoDB_IO_r_ops>\\d*)\\s+InnoDB_IO_r_bytes:\\s+(?<innoDB_IO_r_bytes>\\d*)\\s+InnoDB_IO_r_wait:\\s+(?<innoDB_IO_r_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_rec_lock_wait:\\s+(?<innoDB_rec_lock_wait>[\\d.]*)\\s+InnoDB_queue_wait:\\s+(?<InnoDB_queue_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_pages_distinct:\\s+(?<InnoDB_pages_distinct>[\\d]*)\\n\"\n| parse regex field=query_block \"SET timestamp=(?<set_timestamp>\\d*);\\n(?<sql_cmd>[\\s\\S]*);\"\n| parse regex field=sql_cmd \"[^a-zA-Z]*(?<sql_cmd_type>[a-zA-Z]+)\\s+\"\n| toUpperCase(sql_cmd_type)\n| fields -query_block\n| count as frequency group by sql_cmd_type | sort by frequency"
    }
   ]
  },
  {
   "title": "Avg Exec Time by Slow SQL Cmds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aliasFormat": "{{sql_cmd_type}}",
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"\n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\s+Tmp_tables:\\s+(?<tmp_tables>\\d*)\\s+Tmp_disk_tables:\\s+(?<temp_disk_tables>\\d*)\\s+Tmp_table_sizes:\\s+(?<tmp_table_sizes>\\d*)\\n\" nodrop // Pttrn3-vrtn1\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\n\" nodrop // Pttrn3-vrtn2\n//| parse regex field=query_block \"# InnoDB_trx_id:\\s+(?<innodb_trx_id>\\S*)\\n\"\n//| parse regex field=query_block \"# QC_Hit:\\s+(?<qc_hit>\\S*)\\s+Full_scan:\\s+(?<full_scan>\\S*)\\s+Full_join:\\s+(?<full_join>\\S+)\\s+Tmp_table:\\s+(?<tmp_table>\\S+)\\s+Tmp_table_on_disk:\\s+(?<tmp_table_on_disk>\\S+)\\n\"\n//| parse regex field=query_block \"Filesort:\\s+(?<filesort>\\S*)\\s+Filesort_on_disk:\\s+(?<filesort_on_disk>\\S*)\\s+Merge_passes:\\s+(?<merge_passes>\\S*)\\n\"\n//| parse regex field=query_block \"InnoDB_IO_r_ops:\\s+(?<innoDB_IO_r_ops>\\d*)\\s+InnoDB_IO_r_bytes:\\s+(?<innoDB_IO_r_bytes>\\d*)\\s+InnoDB_IO_r_wait:\\s+(?<innoDB_IO_r_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_rec_lock_wait:\\s+(?<innoDB_rec_lock_wait>[\\d.]*)\\s+InnoDB_queue_wait:\\s+(?<InnoDB_queue_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_pages_distinct:\\s+(?<InnoDB_pages_distinct>[\\d]*)\\n\"\n| parse regex field=query_block \"SET timestamp=(?<set_timestamp>\\d*);\\n(?<sql_cmd>[\\s\\S]*);\"\n| parse regex field=sql_cmd \"[^a-zA-Z]*(?<sql_cmd_type>[a-zA-Z]+)\\s+\"\n| toUpperCase(sql_cmd_type)\n| fields -query_block\n| timeslice 900s\n| avg(query_time) as avg_query_time group by _timeslice, sql_cmd_type"
    }
   ]
  },
  {
   "title": "Slow Queries Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"\n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n//| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n//| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n| timeslice 1h\n| count as queries_count by _timeslice"
    }
   ]
  },
  {
   "title": "Excessive Slow Queries Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"\n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n//| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\s+Tmp_tables:\\s+(?<tmp_tables>\\d*)\\s+Tmp_disk_tables:\\s+(?<temp_disk_tables>\\d*)\\s+Tmp_table_sizes:\\s+(?<tmp_table_sizes>\\d*)\\n\" nodrop // Pttrn3-vrtn1\n//| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\n\" nodrop // Pttrn3-vrtn2\n| num(query_time)\n| where query_time >= 5 \n| timeslice 1h\n| count as queries_count by _timeslice"
    }
   ]
  },
  {
   "title": "Top 10 Slow Queries by Average Execution Time",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"  \n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\s+Tmp_tables:\\s+(?<tmp_tables>\\d*)\\s+Tmp_disk_tables:\\s+(?<temp_disk_tables>\\d*)\\s+Tmp_table_sizes:\\s+(?<tmp_table_sizes>\\d*)\\n\" nodrop // Pttrn3-vrtn1\n| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\n\" nodrop // Pttrn3-vrtn2\n//| parse regex field=query_block \"# InnoDB_trx_id:\\s+(?<innodb_trx_id>\\S*)\\n\"\n//| parse regex field=query_block \"# QC_Hit:\\s+(?<qc_hit>\\S*)\\s+Full_scan:\\s+(?<full_scan>\\S*)\\s+Full_join:\\s+(?<full_join>\\S+)\\s+Tmp_table:\\s+(?<tmp_table>\\S+)\\s+Tmp_table_on_disk:\\s+(?<tmp_table_on_disk>\\S+)\\n\"\n//| parse regex field=query_block \"Filesort:\\s+(?<filesort>\\S*)\\s+Filesort_on_disk:\\s+(?<filesort_on_disk>\\S*)\\s+Merge_passes:\\s+(?<merge_passes>\\S*)\\n\"\n//| parse regex field=query_block \"InnoDB_IO_r_ops:\\s+(?<innoDB_IO_r_ops>\\d*)\\s+InnoDB_IO_r_bytes:\\s+(?<innoDB_IO_r_bytes>\\d*)\\s+InnoDB_IO_r_wait:\\s+(?<innoDB_IO_r_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_rec_lock_wait:\\s+(?<innoDB_rec_lock_wait>[\\d.]*)\\s+InnoDB_queue_wait:\\s+(?<InnoDB_queue_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_pages_distinct:\\s+(?<InnoDB_pages_distinct>[\\d]*)\\n\"\n| parse regex field=query_block \"SET timestamp=(?<set_timestamp>\\d*);\\n(?<sql_cmd>[\\s\\S]*);\"\n| fields -query_block\n| avg(query_time) as avg_time, sum(query_time) as Total_time, min(query_time) as min_time, max(query_time) as max_time, avg(rows_examined) as Avg_rows_examined, avg(rows_sent) as Avg_Rows_Sent, avg(Lock_Time) as Avg_Lock_time, count as frequency group by sql_cmd \n| sort by avg_time | limit 10"
    }
   ]
  },
  {
   "title": "Top 10 Excessive Slow Queries by Frequency",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "_sourceCategory=$source_category \"User@Host\" \"Query_time\"\n| parse regex \"(?<query_block># User@Host:[\\S\\s]+?SET timestamp=\\d+;[\\S\\s]+?;)\" multi\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\" nodrop // Pttrn1-vrtn1\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @\\s+\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" nodrop // Pttrn1-vrtn2\n| parse regex field=query_block \"# User@Host: \\S+?\\[(?<user>\\S*?)\\] @ (?<host_name>\\S+)\\s\\[(?<ip_addr>\\S*?)\\]\\s+Id: (?<Id>\\d{1,10})\" // Pttrn1-vrtn3\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d.]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d.]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d.]*)\\s+Rows_read:\\s+(?<rows_read>[\\d.]*)\\n\" nodrop // Pttrn2-vrtn1\n| parse regex field=query_block \"Schema: (?<schema>(?:\\S*|\\s)?)\\s*Last_errno[\\s\\S]+?\\s+Killed:\\s+\\d+\\n\" nodrop // Pttrn2-vrtn2\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\\s+Rows_affected:\\s+(?<rows_affected>[\\d]*)\\s+\" nodrop // Pttrn2-vrtn3\n| parse regex field=query_block \"Query_time:\\s+(?<query_time>[\\d.]*)\\s+Lock_time:\\s+(?<lock_time>[\\d.]*)\\s+Rows_sent:\\s+(?<rows_sent>[\\d]*)\\s+Rows_examined:\\s+(?<rows_examined>[\\d]*)\" // Pttrn2-vrtn4\n| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\s+Tmp_tables:\\s+(?<tmp_tables>\\d*)\\s+Tmp_disk_tables:\\s+(?<temp_disk_tables>\\d*)\\s+Tmp_table_sizes:\\s+(?<tmp_table_sizes>\\d*)\\n\" nodrop // Pttrn3-vrtn1\n| parse regex field=query_block \"# Bytes_sent:\\s+(?<bytes_sent>\\d*)\\n\" nodrop // Pttrn3-vrtn2\n//| parse regex field=query_block \"# InnoDB_trx_id:\\s+(?<innodb_trx_id>\\S*)\\n\"\n//| parse regex field=query_block \"# QC_Hit:\\s+(?<qc_hit>\\S*)\\s+Full_scan:\\s+(?<full_scan>\\S*)\\s+Full_join:\\s+(?<full_join>\\S+)\\s+Tmp_table:\\s+(?<tmp_table>\\S+)\\s+Tmp_table_on_disk:\\s+(?<tmp_table_on_disk>\\S+)\\n\"\n//| parse regex field=query_block \"Filesort:\\s+(?<filesort>\\S*)\\s+Filesort_on_disk:\\s+(?<filesort_on_disk>\\S*)\\s+Merge_passes:\\s+(?<merge_passes>\\S*)\\n\"\n//| parse regex field=query_block \"InnoDB_IO_r_ops:\\s+(?<innoDB_IO_r_ops>\\d*)\\s+InnoDB_IO_r_bytes:\\s+(?<innoDB_IO_r_bytes>\\d*)\\s+InnoDB_IO_r_wait:\\s+(?<innoDB_IO_r_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_rec_lock_wait:\\s+(?<innoDB_rec_lock_wait>[\\d.]*)\\s+InnoDB_queue_wait:\\s+(?<InnoDB_queue_wait>[\\d.]*)\\n\"\n//| parse regex field=query_block \"InnoDB_pages_distinct:\\s+(?<InnoDB_pages_distinct>[\\d]*)\\n\"\n| parse regex field=query_block \"SET timestamp=(?<set_timestamp>\\d*);\\n(?<sql_cmd>[\\s\\S]*);\"\n| fields -query_block\n| num (query_time)\n| where query_time >= 5\n| count as frequency, sum(query_time) as Total_time, min(query_time) as min_time, max(query_time) as max_time, avg(query_time) as avg_time, avg(rows_examined) as Avg_rows_examined, avg(rows_sent) as Avg_Rows_Sent, avg(Lock_Time) as Avg_Lock_time group by sql_cmd\n| sort by frequency | limit 10"
    }
   ]
  }
 ]
}